site: Hydra
url: https://busterbenson.github.io/hydra
description: This is a personal mythology that helps us grow even when things are
  chaotic.
twitter: 
  username: '@buster'
  card: summary
  creator: 
author:
  twitter: '@buster'
  name: 
  avatar: 
  email: 
  url: https://busterbenson.com
permalink: pretty
baseurl: '/hydra'
highlighter: none
exclude:
- ".jekyll-cache"
compress_html:
  clippings: all
  comments:
  - "<!-- "
  - " -->"
sass:
  sass_dir: _sass
  style: :compressed
plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  tags:
    output: true
    permalink: /tag/:path/
defaults:
  -
    scope:
      path: "/hydra"
      type: "default"
    values:
      layout: "default"
  -
    scope:
      path: "/pages"
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "/posts"
      type: "posts"
    values:
      layout: "post"


